# Generated by Django 5.1.3 on 2025-02-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorting_feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationcriteria',
            name='required_constructs',
            field=models.JSONField(default=list, help_text="List of required constructs (e.g., ['while loop', 'function'])."),
        ),
    ]
