# Generated by Django 5.1.3 on 2025-01-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorting_feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the evaluation criterion.', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this criterion is active.')),
            ],
            options={
                'verbose_name_plural': 'Evaluation Criteria',
            },
        ),
    ]
