# Generated by Django 5.1.3 on 2025-02-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorting_feedback', '0007_evaluation_tutor_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationcriteria',
            name='submission_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
