# Generated by Django 5.1.3 on 2025-02-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorting_feedback', '0011_evaluationcriteria_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationcriteria',
            name='allowed_loop_types',
            field=models.JSONField(blank=True, default=None, help_text="Allowed loop types (e.g., ['for', 'while']).", null=True),
        ),
        migrations.AddField(
            model_name='evaluationcriteria',
            name='max_loop_iterations',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum allowed iterations for loops.', null=True),
        ),
    ]
