# Generated by Django 5.1.3 on 2025-02-15 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorting_feedback', '0014_remove_evaluationcriteria_allowed_loop_types_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentperformance',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='studentperformance',
            name='strength_areas',
        ),
        migrations.RemoveField(
            model_name='studentperformance',
            name='weakness_areas',
        ),
        migrations.AddField(
            model_name='studentperformance',
            name='accuracy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='studentperformance',
            name='strengths',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentperformance',
            name='total_submissions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentperformance',
            name='weaknesses',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
