# Generated by Django 5.1.3 on 2025-02-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorting_feedback', '0015_remove_studentperformance_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentperformance',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='strengths',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='weaknesses',
            field=models.JSONField(default=dict),
        ),
    ]
