# Generated by Django 5.1.3 on 2025-02-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorting_feedback', '0019_remove_evaluation_criteria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationcriteria',
            name='detected_constructs',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='evaluationcriteria',
            name='missing_constructs',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
